package com.springboot.model;

import java.io.Serializable;
import com.springboot.model.Details;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName ="employeedetails")
public class Employee implements Serializable {

	private static final long serialVersionUID = 1L;
	private String employeeId;
	private String employeeName;
	private String employeelastName;
	private String employeeage;
	private Details address;

	
	@DynamoDBHashKey(attributeName = "employeeId")
	@DynamoDBAutoGeneratedKey
	public String getEmployeeid() {
		return employeeId;
	}
	public void setEmployeeid(String employeeids) {
		this.employeeId = employeeids;
	}
	@DynamoDBAttribute
	public String getEmployeeName() {
		return employeeName;
	}
	public void setEmployeeName(String employeeNames) {
		this.employeeName = employeeNames;
	}
	@DynamoDBRangeKey
	public String getEmployeelastName() {
		return employeelastName;
	}

	public void setEmployeelastName(String lastName) 
	{
		this.employeelastName = lastName;
	}

	@DynamoDBAttribute
	public String getEmployeeAge() {
		return employeeage;
	}

	public void setEmployeeAge(String age) {
		this.employeeage = age;
	}

	@DynamoDBAttribute
	public Details getAddress() {
		return address;
	}

	public void setAddress(Details address) {
		this.address = address;
	}
}
